In [126]:
import pandas as pd
pd.options.display.max_columns = None

- selecionar os melhores jogadores para cada posicao

In [127]:
players = pd.read_csv("../data/processed/players.csv")

player_stats = pd.read_csv("../data/processed/player_stats.csv")

In [128]:
players.head(2)

,id,feedId,squadId,firstName,lastName,position,cost,status,isLocked,totalPoints,avgPoints,lastRoundPoints,positionRank,nextFixture,scores,scores.1,scores.2,scores.3,scores.4,1,2,3,4,5
0,1,11627,7,Bryce,Heem,center,0,eliminated,False,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,2,17143,7,Angus,Ta'avao,prop,4500000,uncertain,False,64.0,16.0,37.0,9.0,24,NaN,7.0,6.0,14.0,37.0,1.6,1.4,1.2,1.7,2.0

In [129]:
player_stats.head(2)

,id,tries,assists,conversions,penalties,dropGoals,tackles,linebreaks,linebreakAssists,turnovers,interceptions,defendersBeaten,lineoutsWon,scrumsWon,metresGained,gamesPlayed,penaltiesConceded,errors,yellowCards,redCards,offloads
0,2,1,0,0,0,0,32,1,0,2,0,0,0,1,8,4,3,0,0,0,0
1,3,0,0,0,0,0,37,0,0,0,0,0,0,5,8,4,5,1,0,0,0

In [130]:
players = players.merge(player_stats, on='id', how='inner').query("status != 'eliminated' ") #and status != 'injured'

In [131]:
players.head()

,id,feedId,squadId,firstName,lastName,position,cost,status,isLocked,totalPoints,avgPoints,lastRoundPoints,positionRank,nextFixture,scores,scores.1,scores.2,scores.3,scores.4,1,2,3,4,5,tries,assists,conversions,penalties,dropGoals,tackles,linebreaks,linebreakAssists,turnovers,interceptions,defendersBeaten,lineoutsWon,scrumsWon,metresGained,gamesPlayed,penaltiesConceded,errors,yellowCards,redCards,offloads
0,2,17143,7,Angus,Ta'avao,prop,4500000,uncertain,False,64.0,16.0,37.0,9.0,24,NaN,7.0,6.0,14.0,37.0,1.6,1.4,1.2,1.7,2.0,1,0,0,0,0,32,1,0,2,0,0,0,1,8,4,3,0,0,0,0
1,3,19785,7,Ofa,Tu'ungafasi,prop,6000000,uncertain,False,42.0,10.5,5.0,25.0,24,NaN,14.0,7.0,16.0,5.0,15.4,14.7,13.0,9.1,8.9,0,0,0,0,0,37,0,0,0,0,0,0,5,8,4,5,1,0,0,0
2,4,23552,7,Marcel,Renata,prop,5000000,uncertain,False,50.0,12.5,9.0,14.0,24,NaN,13.0,9.0,19.0,9.0,3.6,3.5,3.2,2.8,2.7,0,0,0,0,0,41,0,0,0,0,0,0,5,11,4,3,1,0,0,0
3,6,55877,7,Josh,Fusitu'a,prop,4000000,uncertain,False,44.0,11.0,10.0,23.0,24,NaN,6.0,9.0,19.0,10.0,0.3,0.3,0.2,0.5,0.5,0,0,0,0,0,31,0,0,1,0,2,0,1,43,4,4,0,1,0,0
4,10,23342,7,Ricky,Riccitelli,hooker,7000000,uncertain,False,189.0,47.3,40.0,1.0,24,NaN,52.0,47.0,50.0,40.0,33.7,39.8,53.1,57.7,57.0,2,1,0,0,0,66,0,1,2,0,3,44,8,44,4,3,0,0,0,2

In [132]:
players.query("position == 'lock'").head(4)

,id,feedId,squadId,firstName,lastName,position,cost,status,isLocked,totalPoints,avgPoints,lastRoundPoints,positionRank,nextFixture,scores,scores.1,scores.2,scores.3,scores.4,1,2,3,4,5,tries,assists,conversions,penalties,dropGoals,tackles,linebreaks,linebreakAssists,turnovers,interceptions,defendersBeaten,lineoutsWon,scrumsWon,metresGained,gamesPlayed,penaltiesConceded,errors,yellowCards,redCards,offloads
6,12,29251,7,Laghlan,McWhannell,lock,3000000,injured,False,30.0,15.0,NaN,28.0,24,NaN,16.0,14.0,NaN,NaN,0.7,1.0,0.3,0.3,0.2,0,0,0,0,0,16,0,0,2,0,0,6,3,12,2,0,0,0,0,0
7,13,60392,7,Cam,Christie,lock,2500000,uncertain,False,39.0,19.5,36.0,26.0,24,NaN,NaN,NaN,3.0,36.0,0.1,0.1,0.1,0.3,0.3,0,0,0,0,0,20,0,0,0,0,0,6,1,26,2,1,2,0,0,1
8,14,20765,7,Patrick,Tuipulotu,lock,5000000,uncertain,False,87.0,21.8,24.0,7.0,24,NaN,18.0,9.0,36.0,24.0,36.2,32.8,25.5,26.5,25.7,0,1,0,0,0,58,1,0,1,0,1,7,9,55,4,3,3,0,0,2
9,16,56225,7,Josh,Beehre,lock,3500000,uncertain,False,95.0,31.7,31.0,6.0,24,NaN,NaN,19.0,45.0,31.0,0.1,0.1,0.3,1.0,1.2,0,0,0,0,0,58,1,0,0,1,5,10,4,52,3,1,1,0,0,0

In [133]:
positions = {
                'prop':'prop',
                'hooker':'hooker', 
                'lock': 'lock',
                'loose_forward': 'loose_forward', 
                'fly_half':'fly_half',
                'center':'midfield',
                'scrum_half': 'half_back',
                'outside_back':'back_three',
            }

players['position'] = players['position'].map(positions)

In [134]:
import pandas as pd
from mip import Model, xsum, maximize, BINARY

# Constants
BUDGET = 100_000_000
MAX_PLAYERS_TEAM = 4

positions = {
    'prop': 2,
    'hooker': 1,
    'lock': 2,
    'loose_forward': 3,
    'half_back': 1,
    'fly_half': 1,
    'midfield': 2,
    'back_three': 3
}

# Load player data (assuming you have a CSV file with player information)
df = players.copy()

# Create the model
model = Model()

# Create binary variables for each player
x = [model.add_var(var_type=BINARY) for i in range(len(df))]

# Objective function: Maximize total player rating
model.objective = maximize(xsum(df.iloc[i]['totalPoints'] * x[i] for i in range(len(df))))

# Budget constraint
model += xsum(df.iloc[i]['cost'] * x[i] for i in range(len(df))) <= BUDGET

# Position constraints
for position, count in positions.items():
    model += xsum(x[i] for i in range(len(df)) if df.iloc[i]['position'] == position) == count

# Team constraint
for team in df['squadId'].unique():
    model += xsum(x[i] for i in range(len(df)) if df.iloc[i]['squadId'] == team) <= MAX_PLAYERS_TEAM

# Solve the model
model.optimize()

# Get the selected players
selected_players = df[pd.Series(x, index=df.index).apply(lambda v: v.x > 0.5)]

# Print the results
print("Selected Players:")
#print(selected_players[['firstName','lastName', 'position', 'squadId', 'cost', 'totalPoints']])
print(f"\nTotal Budget Used: ${selected_players['cost'].sum():,}")
print(f"Total Rating: {selected_players['totalPoints'].sum():.2f}")

Starting solution of the Linear programming relaxation problem using Primal Simplex

Coin0506I Presolve 20 (0) rows, 314 (-7) columns and 942 (-21) elements
Clp1000I sum of infeasibilities 1.45022e-09 - average 7.25112e-11, 287 fixed columns
Coin0506I Presolve 7 (-13) rows, 24 (-290) columns and 55 (-887) elements
Clp0006I 0  Obj 2497.9989 Dual inf 179072.97 (24)
Clp0029I End of values pass after 24 iterations
Clp0000I Optimal - objective value 2498
Clp0000I Optimal - objective value 2498
Coin0511I After Postsolve, objective 2498, infeasibilities - dual 0 (0), primal 0 (0)
Clp0006I 0  Obj 2498 Dual inf 2457 (49)
Clp0014I Perturbing problem by 0.001% of 1.1319021 - largest nonzero change 2.6094575e-05 ( 0.0013047287%) - largest zero change 1.9779715e-05
Clp0000I Optimal - objective value 2498
Clp0000I Optimal - objective value 2498
Clp0000I Optimal - objective value 2498
Coin0511I After Postsolve, objective 2498, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective 2498 - 0 iterations time 0.012, Presolve 0.00, Idiot 0.01

Starting MIP optimization
Cgl0004I processed model has 20 rows, 314 columns (314 integer (314 of which binary)) and 942 elements
Coin3009W Conflict graph built in 0.000 seconds, density: 0.627%
Cgl0015I Clique Strengthening extended 0 cliques, 0 were dominated
Cbc0045I Nauty did not find any useful orbits in time 0.001087
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -2498
Cbc0038I Before mini branch and bound, 314 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of -2498 - took 0.00 seconds
Cbc0012I Integer solution of -2498 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective -2498, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

Selected Players:

Total Budget Used: $89,000,000
Total Rating: 2498.00

In [135]:
squads = pd.read_csv("../data/processed/squads.csv")

(selected_players[['firstName',
                   'lastName', 
                   'position', 
                   'squadId', 
                   'cost', 
                   'totalPoints',
                   'positionRank',
                   'scores.1',
                   'scores.2',
                   'scores.3',
                   'scores.4',
                   'status',
                   '1',
                   '2',
                   '3',
                   '4',
                   '5']]
.merge(squads[['id','name']], left_on='squadId', right_on='id').drop(['id'],axis=1)
.sort_values(by=['position'])
)

,firstName,lastName,position,squadId,cost,totalPoints,positionRank,scores.1,scores.2,scores.3,scores.4,status,1,2,3,4,5,name
5,Sevu,Reece,back_three,1,8500000,182.0,2.0,91.0,33.0,NaN,58.0,uncertain,21.3,39.9,9.9,40.4,44.8,Crusaders
8,Max,Jorgensen,back_three,3,5000000,174.0,3.0,41.0,NaN,51.0,82.0,uncertain,3.3,0.9,1.9,2.0,6.6,NSW Waratahs
14,Kyren,Taumoefolau,back_three,10,4000000,219.0,1.0,82.0,73.0,13.0,51.0,not-selected,0.9,6.7,40.9,29.3,22.5,Moana Pasifika
1,Damian,McKenzie,fly_half,8,10000000,230.0,1.0,104.0,48.0,78.0,NaN,injured,45.9,66.3,70.9,21.0,22.7,Chiefs
6,Cam,Roigard,half_back,2,7500000,198.0,1.0,42.0,85.0,24.0,47.0,uncertain,57.7,66.7,73.4,34.7,44.1,Hurricanes
0,Ricky,Riccitelli,hooker,7,7000000,189.0,1.0,52.0,47.0,50.0,40.0,uncertain,33.7,39.8,53.1,57.7,57.0,Blues
4,Antonio,Shalfoon,lock,1,3500000,110.0,1.0,25.0,59.0,NaN,26.0,uncertain,0.7,1.5,0.8,14.9,16.0,Crusaders
11,Darcy,Swain,lock,9,4000000,108.0,2.0,29.0,22.0,36.0,21.0,uncertain,3.4,12.5,35.0,37.8,35.8,Western Force
7,Harry,Wilson,loose_forward,11,5500000,160.0,3.0,NaN,43.0,49.0,68.0,uncertain,0.6,3.6,4.0,7.9,16.5,Queensland Reds
12,Carlo,Tizzano,loose_forward,9,4500000,209.0,1.0,68.0,51.0,51.0,39.0,uncertain,7.3,19.1,38.1,52.2,53.1,Western Force
13,Ardie,Savea,loose_forward,10,7500000,165.0,2.0,42.0,29.0,81.0,13.0,not-selected,72.3,76.3,68.0,82.9,65.9,Moana Pasifika
2,Anton,Lienert-Brown,midfield,8,8500000,151.0,2.0,4.0,37.0,78.0,32.0,uncertain,7.9,14.0,23.8,39.3,39.7,Chiefs
3,Quinn,Tupaea,midfield,8,6500000,198.0,1.0,32.0,98.0,59.0,9.0,uncertain,19.1,17.6,50.2,61.6,59.1,Chiefs
9,Marley,Pearce,prop,9,2500000,110.0,1.0,34.0,27.0,36.0,13.0,uncertain,0.3,13.5,38.4,46.7,44.4,Western Force
10,Tom,Robertson,prop,9,4500000,95.0,2.0,7.0,30.0,47.0,11.0,uncertain,1.4,1.3,6.0,21.3,18.8,Western Force